# Generated by Django 6.0.3 on 2026-04-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
